#ifndef _BS_H_
#define _BS_H_

#include <uEZ.h>
#include "DIALOG.h"

typedef enum command{

	EXIT,
	
	SWITCH_CONTEXT_TO_LEDS_CONTROLLER,
	SWITCH_CONTEXT_TO_SENSORS_CONTROLLER,
	SWITCH_CONTEXT_TO_DEBUG_MODBUS_CONTROLLER,
	EXIT_CONTROLLER,
	
	INIT_LEDS_CONTROLLER,
	CHANGE_LED_STATUS_1,
	CHANGE_LED_STATUS_2,
	CHANGE_LED_STATUS_3,
	CHANGE_LED_STATUS_4,
	CHANGE_LED_STATUS_5,
	CHANGE_LED_STATUS_6,
	UPDATE_LEDS_STATUS,
	
	INIT_SENSORS_CONTROLLER,
	CHANGE_DELAY_QUERY_FROM_WINDOW,
	CHANGE_DELAY_QUERY_FROM_CONTROLLER,
	NOTIFY_MAX_TEMPERATURE_THRESHOLD_FROM_WINDOW,
	NOTIFY_MAX_TEMPERATURE_THRESHOLD_FROM_CONTROLLER,
	NOTIFY_ALARM_TEMPERATURE_SENSOR_CHANGED_FROM_WINDOW,
	NOTIFY_ALARM_PRESENCE_SENSOR_CHANGED_FROM_WINDOW,
	NOTIFY_NO_LIGHT_SENSOR_CHANGED_FROM_WINDOW,
	UPDATE_SENSORS_STATUS
	
}command;


//destinatario chiamata
typedef enum recipient{

	INTERNAL,
	EXTERNAL
	
}recipient;


typedef struct message{
	int i;
}message;



void BS_wrapper(command signal, recipient rec, void *obj);

#endif